kind: Deployment
apiVersion: apps/v1
metadata:
  name: nodesysout
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodesysout-app
  template:
    metadata:
      labels:
        app: nodesysout-app
    spec:
      containers:
        - name: nodesysout
          image: nodejs-image:latest
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"
---
kind: Service
apiVersion: v1
metadata:
  name: nodesysout-app-svc
spec:
ports:
  - name: http-3001
    port: 3001
    protocol: TCP
    targetPort: 3001
selector:
  app: nodesysout-app